services:

  person-postgres:
    image: postgres:17
    container_name: person-postgres
    entrypoint:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: person
    volumes:
      - ./infrastructure/databases/person:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  keycloak-postgres:
    image: postgres:17
    container_name: keycloak-postgres
    entrypoint:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 20

  person-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: person-postgres-exporter
    depends_on:
      - person-postgres:
          condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:postgres@person-postgres:5432/postgres?sslmode=disable
    ports:
      - "9188:9187"

  keycloak-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: keycloak-postgres-exporter
    depends_on:
      - person-postgres:
          condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgresql://keycloak:keycloak@keycloak-postgres:5432/keycloak?sslmode=disable
    ports:
      - "9189:9187"

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: individuals-keycloak
    command:
      - start-dev
      - import-realm
      - --health-enabled=true
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      JAVA_OPTS: -Dkeycloak.migration.userExportStrategy=REALM_FILE
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    volumes:
      - ./infrastructure/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      - keycloak-postgres:
          condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9000/healthy/ready || exit1" ]
      interval: 10s
      timeout: 5s
      retries: 30
